### ISSUE TITLE
Compiling on macOS

### ISSUE THREAD

**Issue by moshidev** [dmolina/cec2017real#1]
I've encountered two compilation errors while trying to compile the project in macOS with Clang, I share them there.

1. "fatal error: 'malloc.h' file not found at file cec17_test_func.c". Can be solved removing `#include <malloc.h>`. I've tried both in macOS and CentOS and it seems to work.
2. "auto specifier is a C++11 feature". Can be solved adding `set (CMAKE_CXX_STANDARD 11)` to CMakeLists.txt.

**Comment by yokeman-young** [comment]
I recommend an open-source C++ benchmarking framework for single-objective evolutionary optimization algorithms. You can find it at https://github.com/yangyongkang2000/SEvoBench.

**Comment by dmolina** [comment]
Thank you, I give it a glance, it seems very nice.
